-- Enable RLS
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- News Table
create table news (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text, -- Rich text or Markdown
  image_url text,
  published boolean default true
);

alter table news enable row level security;

create policy "Public News are viewable by everyone"
  on news for select
  using ( true );

create policy "Users can insert News"
  on news for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update News"
  on news for update
  using ( auth.role() = 'authenticated' );

create policy "Users can delete News"
  on news for delete
  using ( auth.role() = 'authenticated' );

-- Shows Table
create table shows (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  image_url text,
  slug text unique not null,
  featured boolean default false
);

alter table shows enable row level security;

create policy "Public Shows are viewable by everyone"
  on shows for select
  using ( true );

create policy "Users can insert Shows"
  on shows for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update Shows"
  on shows for update
  using ( auth.role() = 'authenticated' );

create policy "Users can delete Shows"
  on shows for delete
  using ( auth.role() = 'authenticated' );

-- Agenda Table
create table agenda (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  show_id bigint references shows(id),
  date timestamp with time zone not null,
  location text not null,
  link text -- Ticket link or map
);

alter table agenda enable row level security;

create policy "Public Agenda is viewable by everyone"
  on agenda for select
  using ( true );

create policy "Users can insert Agenda"
  on agenda for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update Agenda"
  on agenda for update
  using ( auth.role() = 'authenticated' );

create policy "Users can delete Agenda"
  on agenda for delete
  using ( auth.role() = 'authenticated' );

-- Storage Buckets (Images)
insert into storage.buckets (id, name, public) values ('images', 'images', true);

create policy "Public Images are viewable by everyone"
  on storage.objects for select
  using ( bucket_id = 'images' );

create policy "Authenticated users can upload images"
  on storage.objects for insert
  with check ( bucket_id = 'images' and auth.role() = 'authenticated' );
